/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VoicemailApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class VoicemailApiTests
    {
        private VoicemailApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VoicemailApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VoicemailApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' VoicemailApi
            //Assert.IsInstanceOfType(typeof(VoicemailApi), instance, "instance is a VoicemailApi");
        }

        
        /// <summary>
        /// Test GetAccountVoicemail
        /// </summary>
        [Test]
        public void GetAccountVoicemailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //string voicemailId = null;
            //var response = instance.GetAccountVoicemail(accountId, voicemailId);
            //Assert.IsInstanceOf<VoicemailFull> (response, "response is VoicemailFull");
        }
        
        /// <summary>
        /// Test ListAccountVoicemail
        /// </summary>
        [Test]
        public void ListAccountVoicemailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //List<string> filtersId = null;
            //string filtersFrom = null;
            //string filtersTo = null;
            //bool? filtersIsNew = null;
            //string filtersCreatedAt = null;
            //List<string> filtersExtension = null;
            //string sortId = null;
            //string sortCreatedAt = null;
            //int? limit = null;
            //int? offset = null;
            //string fields = null;
            //var response = instance.ListAccountVoicemail(accountId, filtersId, filtersFrom, filtersTo, filtersIsNew, filtersCreatedAt, filtersExtension, sortId, sortCreatedAt, limit, offset, fields);
            //Assert.IsInstanceOf<ListVoicemail> (response, "response is ListVoicemail");
        }
        
        /// <summary>
        /// Test PatchAccountVoicemail
        /// </summary>
        [Test]
        public void PatchAccountVoicemailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //string voicemailId = null;
            //PatchVoicemailParams data = null;
            //var response = instance.PatchAccountVoicemail(accountId, voicemailId, data);
            //Assert.IsInstanceOf<VoicemailFull> (response, "response is VoicemailFull");
        }
        
    }

}
