/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ReplaceExtensionParams
    /// </summary>
    [DataContract]
    public partial class ReplaceExtensionParams :  IEquatable<ReplaceExtensionParams>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplaceExtensionParams" /> class.
        /// </summary>
        /// <param name="Voicemail">Voicemail object.</param>
        /// <param name="CallNotifications">Call Notifications object.</param>
        /// <param name="NameGreeting">Recording lookup object.</param>
        /// <param name="Name">Name (required).</param>
        /// <param name="Timezone">Timezone.</param>
        /// <param name="IncludeInDirectory">Include in dial-by-name directory.</param>
        /// <param name="Extension">Extension number (required).</param>
        /// <param name="EnableOutboundCalls">Enable outgoing calls.</param>
        /// <param name="UsageType">Extension type.</param>
        /// <param name="FullName">Contact name.</param>
        /// <param name="EnableCallWaiting">Enable Call Waiting.</param>
        /// <param name="CallerId">Caller ID.</param>
        /// <param name="LocalAreaCode">Local area code.</param>
        /// <param name="Route">Route object lookup (must belong to this extension).</param>
        public ReplaceExtensionParams(Voicemail Voicemail = default(Voicemail), CallNotifications CallNotifications = default(CallNotifications), Object NameGreeting = default(Object), string Name = default(string), string Timezone = default(string), bool? IncludeInDirectory = default(bool?), int? Extension = default(int?), bool? EnableOutboundCalls = default(bool?), string UsageType = default(string), string FullName = default(string), bool? EnableCallWaiting = default(bool?), string CallerId = default(string), int? LocalAreaCode = default(int?), string Route = default(string))
        {
            this.Voicemail = Voicemail;
            this.CallNotifications = CallNotifications;
            this.NameGreeting = NameGreeting;
            this.Name = Name;
            this.Timezone = Timezone;
            this.IncludeInDirectory = IncludeInDirectory;
            this.Extension = Extension;
            this.EnableOutboundCalls = EnableOutboundCalls;
            this.UsageType = UsageType;
            this.FullName = FullName;
            this.EnableCallWaiting = EnableCallWaiting;
            this.CallerId = CallerId;
            this.LocalAreaCode = LocalAreaCode;
            this.Route = Route;
        }
        
        /// <summary>
        /// Voicemail object
        /// </summary>
        /// <value>Voicemail object</value>
        [DataMember(Name="voicemail", EmitDefaultValue=false)]
        public Voicemail Voicemail { get; set; }
        /// <summary>
        /// Call Notifications object
        /// </summary>
        /// <value>Call Notifications object</value>
        [DataMember(Name="call_notifications", EmitDefaultValue=false)]
        public CallNotifications CallNotifications { get; set; }
        /// <summary>
        /// Recording lookup object
        /// </summary>
        /// <value>Recording lookup object</value>
        [DataMember(Name="name_greeting", EmitDefaultValue=false)]
        public Object NameGreeting { get; set; }
        /// <summary>
        /// Name (required)
        /// </summary>
        /// <value>Name (required)</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Timezone
        /// </summary>
        /// <value>Timezone</value>
        [DataMember(Name="timezone", EmitDefaultValue=false)]
        public string Timezone { get; set; }
        /// <summary>
        /// Include in dial-by-name directory
        /// </summary>
        /// <value>Include in dial-by-name directory</value>
        [DataMember(Name="include_in_directory", EmitDefaultValue=false)]
        public bool? IncludeInDirectory { get; set; }
        /// <summary>
        /// Extension number (required)
        /// </summary>
        /// <value>Extension number (required)</value>
        [DataMember(Name="extension", EmitDefaultValue=false)]
        public int? Extension { get; set; }
        /// <summary>
        /// Enable outgoing calls
        /// </summary>
        /// <value>Enable outgoing calls</value>
        [DataMember(Name="enable_outbound_calls", EmitDefaultValue=false)]
        public bool? EnableOutboundCalls { get; set; }
        /// <summary>
        /// Extension type
        /// </summary>
        /// <value>Extension type</value>
        [DataMember(Name="usage_type", EmitDefaultValue=false)]
        public string UsageType { get; set; }
        /// <summary>
        /// Contact name
        /// </summary>
        /// <value>Contact name</value>
        [DataMember(Name="full_name", EmitDefaultValue=false)]
        public string FullName { get; set; }
        /// <summary>
        /// Enable Call Waiting
        /// </summary>
        /// <value>Enable Call Waiting</value>
        [DataMember(Name="enable_call_waiting", EmitDefaultValue=false)]
        public bool? EnableCallWaiting { get; set; }
        /// <summary>
        /// Caller ID
        /// </summary>
        /// <value>Caller ID</value>
        [DataMember(Name="caller_id", EmitDefaultValue=false)]
        public string CallerId { get; set; }
        /// <summary>
        /// Local area code
        /// </summary>
        /// <value>Local area code</value>
        [DataMember(Name="local_area_code", EmitDefaultValue=false)]
        public int? LocalAreaCode { get; set; }
        /// <summary>
        /// Route object lookup (must belong to this extension)
        /// </summary>
        /// <value>Route object lookup (must belong to this extension)</value>
        [DataMember(Name="route", EmitDefaultValue=false)]
        public string Route { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReplaceExtensionParams {\n");
            sb.Append("  Voicemail: ").Append(Voicemail).Append("\n");
            sb.Append("  CallNotifications: ").Append(CallNotifications).Append("\n");
            sb.Append("  NameGreeting: ").Append(NameGreeting).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("  IncludeInDirectory: ").Append(IncludeInDirectory).Append("\n");
            sb.Append("  Extension: ").Append(Extension).Append("\n");
            sb.Append("  EnableOutboundCalls: ").Append(EnableOutboundCalls).Append("\n");
            sb.Append("  UsageType: ").Append(UsageType).Append("\n");
            sb.Append("  FullName: ").Append(FullName).Append("\n");
            sb.Append("  EnableCallWaiting: ").Append(EnableCallWaiting).Append("\n");
            sb.Append("  CallerId: ").Append(CallerId).Append("\n");
            sb.Append("  LocalAreaCode: ").Append(LocalAreaCode).Append("\n");
            sb.Append("  Route: ").Append(Route).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ReplaceExtensionParams);
        }

        /// <summary>
        /// Returns true if ReplaceExtensionParams instances are equal
        /// </summary>
        /// <param name="other">Instance of ReplaceExtensionParams to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReplaceExtensionParams other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Voicemail == other.Voicemail ||
                    this.Voicemail != null &&
                    this.Voicemail.Equals(other.Voicemail)
                ) && 
                (
                    this.CallNotifications == other.CallNotifications ||
                    this.CallNotifications != null &&
                    this.CallNotifications.Equals(other.CallNotifications)
                ) && 
                (
                    this.NameGreeting == other.NameGreeting ||
                    this.NameGreeting != null &&
                    this.NameGreeting.Equals(other.NameGreeting)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Timezone == other.Timezone ||
                    this.Timezone != null &&
                    this.Timezone.Equals(other.Timezone)
                ) && 
                (
                    this.IncludeInDirectory == other.IncludeInDirectory ||
                    this.IncludeInDirectory != null &&
                    this.IncludeInDirectory.Equals(other.IncludeInDirectory)
                ) && 
                (
                    this.Extension == other.Extension ||
                    this.Extension != null &&
                    this.Extension.Equals(other.Extension)
                ) && 
                (
                    this.EnableOutboundCalls == other.EnableOutboundCalls ||
                    this.EnableOutboundCalls != null &&
                    this.EnableOutboundCalls.Equals(other.EnableOutboundCalls)
                ) && 
                (
                    this.UsageType == other.UsageType ||
                    this.UsageType != null &&
                    this.UsageType.Equals(other.UsageType)
                ) && 
                (
                    this.FullName == other.FullName ||
                    this.FullName != null &&
                    this.FullName.Equals(other.FullName)
                ) && 
                (
                    this.EnableCallWaiting == other.EnableCallWaiting ||
                    this.EnableCallWaiting != null &&
                    this.EnableCallWaiting.Equals(other.EnableCallWaiting)
                ) && 
                (
                    this.CallerId == other.CallerId ||
                    this.CallerId != null &&
                    this.CallerId.Equals(other.CallerId)
                ) && 
                (
                    this.LocalAreaCode == other.LocalAreaCode ||
                    this.LocalAreaCode != null &&
                    this.LocalAreaCode.Equals(other.LocalAreaCode)
                ) && 
                (
                    this.Route == other.Route ||
                    this.Route != null &&
                    this.Route.Equals(other.Route)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Voicemail != null)
                    hash = hash * 59 + this.Voicemail.GetHashCode();
                if (this.CallNotifications != null)
                    hash = hash * 59 + this.CallNotifications.GetHashCode();
                if (this.NameGreeting != null)
                    hash = hash * 59 + this.NameGreeting.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Timezone != null)
                    hash = hash * 59 + this.Timezone.GetHashCode();
                if (this.IncludeInDirectory != null)
                    hash = hash * 59 + this.IncludeInDirectory.GetHashCode();
                if (this.Extension != null)
                    hash = hash * 59 + this.Extension.GetHashCode();
                if (this.EnableOutboundCalls != null)
                    hash = hash * 59 + this.EnableOutboundCalls.GetHashCode();
                if (this.UsageType != null)
                    hash = hash * 59 + this.UsageType.GetHashCode();
                if (this.FullName != null)
                    hash = hash * 59 + this.FullName.GetHashCode();
                if (this.EnableCallWaiting != null)
                    hash = hash * 59 + this.EnableCallWaiting.GetHashCode();
                if (this.CallerId != null)
                    hash = hash * 59 + this.CallerId.GetHashCode();
                if (this.LocalAreaCode != null)
                    hash = hash * 59 + this.LocalAreaCode.GetHashCode();
                if (this.Route != null)
                    hash = hash * 59 + this.Route.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
