/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetOauthAccessToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetOauthAccessTokenTests
    {
        // TODO uncomment below to declare an instance variable for GetOauthAccessToken
        //private GetOauthAccessToken instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetOauthAccessToken
            //instance = new GetOauthAccessToken();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetOauthAccessToken
        /// </summary>
        [Test]
        public void GetOauthAccessTokenInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetOauthAccessToken
            //Assert.IsInstanceOfType<GetOauthAccessToken> (instance, "variable 'instance' is a GetOauthAccessToken");
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Test]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
        /// <summary>
        /// Test the property 'ScopeDetails'
        /// </summary>
        [Test]
        public void ScopeDetailsTest()
        {
            // TODO unit test for the property 'ScopeDetails'
        }

    }

}
