/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PatchVoicemailParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatchVoicemailParamsTests
    {
        // TODO uncomment below to declare an instance variable for PatchVoicemailParams
        //private PatchVoicemailParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatchVoicemailParams
            //instance = new PatchVoicemailParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatchVoicemailParams
        /// </summary>
        [Test]
        public void PatchVoicemailParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatchVoicemailParams
            //Assert.IsInstanceOfType<PatchVoicemailParams> (instance, "variable 'instance' is a PatchVoicemailParams");
        }

        /// <summary>
        /// Test the property 'IsNew'
        /// </summary>
        [Test]
        public void IsNewTest()
        {
            // TODO unit test for the property 'IsNew'
        }

    }

}
