/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PaymentFull
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentFullTests
    {
        // TODO uncomment below to declare an instance variable for PaymentFull
        //private PaymentFull instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentFull
            //instance = new PaymentFull();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentFull
        /// </summary>
        [Test]
        public void PaymentFullInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentFull
            //Assert.IsInstanceOfType<PaymentFull> (instance, "variable 'instance' is a PaymentFull");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'VoipId'
        /// </summary>
        [Test]
        public void VoipIdTest()
        {
            // TODO unit test for the property 'VoipId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Test]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'DeclineCount'
        /// </summary>
        [Test]
        public void DeclineCountTest()
        {
            // TODO unit test for the property 'DeclineCount'
        }
        /// <summary>
        /// Test the property 'NextChargeDate'
        /// </summary>
        [Test]
        public void NextChargeDateTest()
        {
            // TODO unit test for the property 'NextChargeDate'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'CcToken'
        /// </summary>
        [Test]
        public void CcTokenTest()
        {
            // TODO unit test for the property 'CcToken'
        }
        /// <summary>
        /// Test the property 'CcNumber'
        /// </summary>
        [Test]
        public void CcNumberTest()
        {
            // TODO unit test for the property 'CcNumber'
        }
        /// <summary>
        /// Test the property 'CcExp'
        /// </summary>
        [Test]
        public void CcExpTest()
        {
            // TODO unit test for the property 'CcExp'
        }

    }

}
