/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VoicemailInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VoicemailInputTests
    {
        // TODO uncomment below to declare an instance variable for VoicemailInput
        //private VoicemailInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VoicemailInput
            //instance = new VoicemailInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VoicemailInput
        /// </summary>
        [Test]
        public void VoicemailInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VoicemailInput
            //Assert.IsInstanceOfType<VoicemailInput> (instance, "variable 'instance' is a VoicemailInput");
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Greeting'
        /// </summary>
        [Test]
        public void GreetingTest()
        {
            // TODO unit test for the property 'Greeting'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Test]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }
        /// <summary>
        /// Test the property 'Notifications'
        /// </summary>
        [Test]
        public void NotificationsTest()
        {
            // TODO unit test for the property 'Notifications'
        }
        /// <summary>
        /// Test the property 'Transcription'
        /// </summary>
        [Test]
        public void TranscriptionTest()
        {
            // TODO unit test for the property 'Transcription'
        }

    }

}
