/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentmethodsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create an individual payment method.
        /// </summary>
        /// <remarks>
        /// Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>PaymentFull</returns>
        PaymentFull CreateAccountPaymentMethod (int? accountId, CreatePaymentParams data);

        /// <summary>
        /// Create an individual payment method.
        /// </summary>
        /// <remarks>
        /// Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>ApiResponse of PaymentFull</returns>
        ApiResponse<PaymentFull> CreateAccountPaymentMethodWithHttpInfo (int? accountId, CreatePaymentParams data);
        /// <summary>
        /// Delete an individual payment method.
        /// </summary>
        /// <remarks>
        /// Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>DeleteEntry</returns>
        DeleteEntry DeleteAccountPaymentMethod (int? accountId, int? pmId);

        /// <summary>
        /// Delete an individual payment method.
        /// </summary>
        /// <remarks>
        /// Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>ApiResponse of DeleteEntry</returns>
        ApiResponse<DeleteEntry> DeleteAccountPaymentMethodWithHttpInfo (int? accountId, int? pmId);
        /// <summary>
        /// Show details of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>PaymentFull</returns>
        PaymentFull GetAccountPaymentMethod (int? accountId, int? pmId);

        /// <summary>
        /// Show details of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>ApiResponse of PaymentFull</returns>
        ApiResponse<PaymentFull> GetAccountPaymentMethodWithHttpInfo (int? accountId, int? pmId);
        /// <summary>
        /// Get a list of payment methods for an account.
        /// </summary>
        /// <remarks>
        /// Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>ListPaymentMethods</returns>
        ListPaymentMethods ListAccountPaymentMethods (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null);

        /// <summary>
        /// Get a list of payment methods for an account.
        /// </summary>
        /// <remarks>
        /// Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>ApiResponse of ListPaymentMethods</returns>
        ApiResponse<ListPaymentMethods> ListAccountPaymentMethodsWithHttpInfo (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null);
        /// <summary>
        /// Replace the status of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>PaymentFull</returns>
        PaymentFull PatchAccountPaymentMethod (int? accountId, int? pmId, PatchPaymentParams data = null);

        /// <summary>
        /// Replace the status of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>ApiResponse of PaymentFull</returns>
        ApiResponse<PaymentFull> PatchAccountPaymentMethodWithHttpInfo (int? accountId, int? pmId, PatchPaymentParams data = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create an individual payment method.
        /// </summary>
        /// <remarks>
        /// Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>Task of PaymentFull</returns>
        System.Threading.Tasks.Task<PaymentFull> CreateAccountPaymentMethodAsync (int? accountId, CreatePaymentParams data);

        /// <summary>
        /// Create an individual payment method.
        /// </summary>
        /// <remarks>
        /// Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>Task of ApiResponse (PaymentFull)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentFull>> CreateAccountPaymentMethodAsyncWithHttpInfo (int? accountId, CreatePaymentParams data);
        /// <summary>
        /// Delete an individual payment method.
        /// </summary>
        /// <remarks>
        /// Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of DeleteEntry</returns>
        System.Threading.Tasks.Task<DeleteEntry> DeleteAccountPaymentMethodAsync (int? accountId, int? pmId);

        /// <summary>
        /// Delete an individual payment method.
        /// </summary>
        /// <remarks>
        /// Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of ApiResponse (DeleteEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeleteEntry>> DeleteAccountPaymentMethodAsyncWithHttpInfo (int? accountId, int? pmId);
        /// <summary>
        /// Show details of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of PaymentFull</returns>
        System.Threading.Tasks.Task<PaymentFull> GetAccountPaymentMethodAsync (int? accountId, int? pmId);

        /// <summary>
        /// Show details of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of ApiResponse (PaymentFull)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentFull>> GetAccountPaymentMethodAsyncWithHttpInfo (int? accountId, int? pmId);
        /// <summary>
        /// Get a list of payment methods for an account.
        /// </summary>
        /// <remarks>
        /// Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>Task of ListPaymentMethods</returns>
        System.Threading.Tasks.Task<ListPaymentMethods> ListAccountPaymentMethodsAsync (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null);

        /// <summary>
        /// Get a list of payment methods for an account.
        /// </summary>
        /// <remarks>
        /// Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>Task of ApiResponse (ListPaymentMethods)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListPaymentMethods>> ListAccountPaymentMethodsAsyncWithHttpInfo (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null);
        /// <summary>
        /// Replace the status of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>Task of PaymentFull</returns>
        System.Threading.Tasks.Task<PaymentFull> PatchAccountPaymentMethodAsync (int? accountId, int? pmId, PatchPaymentParams data = null);

        /// <summary>
        /// Replace the status of an individual payment method.
        /// </summary>
        /// <remarks>
        /// Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>Task of ApiResponse (PaymentFull)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentFull>> PatchAccountPaymentMethodAsyncWithHttpInfo (int? accountId, int? pmId, PatchPaymentParams data = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PaymentmethodsApi : IPaymentmethodsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentmethodsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PaymentmethodsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentmethodsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PaymentmethodsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create an individual payment method. Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>PaymentFull</returns>
        public PaymentFull CreateAccountPaymentMethod (int? accountId, CreatePaymentParams data)
        {
             ApiResponse<PaymentFull> localVarResponse = CreateAccountPaymentMethodWithHttpInfo(accountId, data);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create an individual payment method. Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>ApiResponse of PaymentFull</returns>
        public ApiResponse< PaymentFull > CreateAccountPaymentMethodWithHttpInfo (int? accountId, CreatePaymentParams data)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->CreateAccountPaymentMethod");
            // verify the required parameter 'data' is set
            if (data == null)
                throw new ApiException(400, "Missing required parameter 'data' when calling PaymentmethodsApi->CreateAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (data != null && data.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
            }
            else
            {
                localVarPostBody = data; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PaymentFull>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PaymentFull) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaymentFull)));
        }

        /// <summary>
        /// Create an individual payment method. Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>Task of PaymentFull</returns>
        public async System.Threading.Tasks.Task<PaymentFull> CreateAccountPaymentMethodAsync (int? accountId, CreatePaymentParams data)
        {
             ApiResponse<PaymentFull> localVarResponse = await CreateAccountPaymentMethodAsyncWithHttpInfo(accountId, data);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create an individual payment method. Create an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="data">Payment data</param>
        /// <returns>Task of ApiResponse (PaymentFull)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PaymentFull>> CreateAccountPaymentMethodAsyncWithHttpInfo (int? accountId, CreatePaymentParams data)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->CreateAccountPaymentMethod");
            // verify the required parameter 'data' is set
            if (data == null)
                throw new ApiException(400, "Missing required parameter 'data' when calling PaymentmethodsApi->CreateAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (data != null && data.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
            }
            else
            {
                localVarPostBody = data; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PaymentFull>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PaymentFull) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaymentFull)));
        }

        /// <summary>
        /// Delete an individual payment method. Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>DeleteEntry</returns>
        public DeleteEntry DeleteAccountPaymentMethod (int? accountId, int? pmId)
        {
             ApiResponse<DeleteEntry> localVarResponse = DeleteAccountPaymentMethodWithHttpInfo(accountId, pmId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an individual payment method. Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>ApiResponse of DeleteEntry</returns>
        public ApiResponse< DeleteEntry > DeleteAccountPaymentMethodWithHttpInfo (int? accountId, int? pmId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->DeleteAccountPaymentMethod");
            // verify the required parameter 'pmId' is set
            if (pmId == null)
                throw new ApiException(400, "Missing required parameter 'pmId' when calling PaymentmethodsApi->DeleteAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods/{pm_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (pmId != null) localVarPathParams.Add("pm_id", Configuration.ApiClient.ParameterToString(pmId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeleteEntry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeleteEntry) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeleteEntry)));
        }

        /// <summary>
        /// Delete an individual payment method. Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of DeleteEntry</returns>
        public async System.Threading.Tasks.Task<DeleteEntry> DeleteAccountPaymentMethodAsync (int? accountId, int? pmId)
        {
             ApiResponse<DeleteEntry> localVarResponse = await DeleteAccountPaymentMethodAsyncWithHttpInfo(accountId, pmId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete an individual payment method. Delete an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of ApiResponse (DeleteEntry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeleteEntry>> DeleteAccountPaymentMethodAsyncWithHttpInfo (int? accountId, int? pmId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->DeleteAccountPaymentMethod");
            // verify the required parameter 'pmId' is set
            if (pmId == null)
                throw new ApiException(400, "Missing required parameter 'pmId' when calling PaymentmethodsApi->DeleteAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods/{pm_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (pmId != null) localVarPathParams.Add("pm_id", Configuration.ApiClient.ParameterToString(pmId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeleteEntry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DeleteEntry) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeleteEntry)));
        }

        /// <summary>
        /// Show details of an individual payment method. Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>PaymentFull</returns>
        public PaymentFull GetAccountPaymentMethod (int? accountId, int? pmId)
        {
             ApiResponse<PaymentFull> localVarResponse = GetAccountPaymentMethodWithHttpInfo(accountId, pmId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Show details of an individual payment method. Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>ApiResponse of PaymentFull</returns>
        public ApiResponse< PaymentFull > GetAccountPaymentMethodWithHttpInfo (int? accountId, int? pmId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->GetAccountPaymentMethod");
            // verify the required parameter 'pmId' is set
            if (pmId == null)
                throw new ApiException(400, "Missing required parameter 'pmId' when calling PaymentmethodsApi->GetAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods/{pm_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (pmId != null) localVarPathParams.Add("pm_id", Configuration.ApiClient.ParameterToString(pmId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PaymentFull>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PaymentFull) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaymentFull)));
        }

        /// <summary>
        /// Show details of an individual payment method. Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of PaymentFull</returns>
        public async System.Threading.Tasks.Task<PaymentFull> GetAccountPaymentMethodAsync (int? accountId, int? pmId)
        {
             ApiResponse<PaymentFull> localVarResponse = await GetAccountPaymentMethodAsyncWithHttpInfo(accountId, pmId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Show details of an individual payment method. Show details of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <returns>Task of ApiResponse (PaymentFull)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PaymentFull>> GetAccountPaymentMethodAsyncWithHttpInfo (int? accountId, int? pmId)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->GetAccountPaymentMethod");
            // verify the required parameter 'pmId' is set
            if (pmId == null)
                throw new ApiException(400, "Missing required parameter 'pmId' when calling PaymentmethodsApi->GetAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods/{pm_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (pmId != null) localVarPathParams.Add("pm_id", Configuration.ApiClient.ParameterToString(pmId)); // path parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PaymentFull>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PaymentFull) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaymentFull)));
        }

        /// <summary>
        /// Get a list of payment methods for an account. Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>ListPaymentMethods</returns>
        public ListPaymentMethods ListAccountPaymentMethods (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null)
        {
             ApiResponse<ListPaymentMethods> localVarResponse = ListAccountPaymentMethodsWithHttpInfo(accountId, filtersId, sortId, limit, offset, fields);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of payment methods for an account. Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>ApiResponse of ListPaymentMethods</returns>
        public ApiResponse< ListPaymentMethods > ListAccountPaymentMethodsWithHttpInfo (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->ListAccountPaymentMethods");

            var localVarPath = "/accounts/{account_id}/payment-methods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (filtersId != null) localVarQueryParams.Add("filters[id]", Configuration.ApiClient.ParameterToString(filtersId)); // query parameter
            if (sortId != null) localVarQueryParams.Add("sort[id]", Configuration.ApiClient.ParameterToString(sortId)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (fields != null) localVarQueryParams.Add("fields", Configuration.ApiClient.ParameterToString(fields)); // query parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAccountPaymentMethods", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListPaymentMethods>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ListPaymentMethods) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListPaymentMethods)));
        }

        /// <summary>
        /// Get a list of payment methods for an account. Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>Task of ListPaymentMethods</returns>
        public async System.Threading.Tasks.Task<ListPaymentMethods> ListAccountPaymentMethodsAsync (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null)
        {
             ApiResponse<ListPaymentMethods> localVarResponse = await ListAccountPaymentMethodsAsyncWithHttpInfo(accountId, filtersId, sortId, limit, offset, fields);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of payment methods for an account. Get a list of payment methods for an account. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="filtersId">ID filter (optional)</param>
        /// <param name="sortId">ID sorting (optional)</param>
        /// <param name="limit">Max results (optional)</param>
        /// <param name="offset">Results to skip (optional)</param>
        /// <param name="fields">Field set (optional)</param>
        /// <returns>Task of ApiResponse (ListPaymentMethods)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListPaymentMethods>> ListAccountPaymentMethodsAsyncWithHttpInfo (int? accountId, List<string> filtersId = null, string sortId = null, int? limit = null, int? offset = null, string fields = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->ListAccountPaymentMethods");

            var localVarPath = "/accounts/{account_id}/payment-methods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (filtersId != null) localVarQueryParams.Add("filters[id]", Configuration.ApiClient.ParameterToString(filtersId)); // query parameter
            if (sortId != null) localVarQueryParams.Add("sort[id]", Configuration.ApiClient.ParameterToString(sortId)); // query parameter
            if (limit != null) localVarQueryParams.Add("limit", Configuration.ApiClient.ParameterToString(limit)); // query parameter
            if (offset != null) localVarQueryParams.Add("offset", Configuration.ApiClient.ParameterToString(offset)); // query parameter
            if (fields != null) localVarQueryParams.Add("fields", Configuration.ApiClient.ParameterToString(fields)); // query parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAccountPaymentMethods", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListPaymentMethods>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ListPaymentMethods) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListPaymentMethods)));
        }

        /// <summary>
        /// Replace the status of an individual payment method. Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>PaymentFull</returns>
        public PaymentFull PatchAccountPaymentMethod (int? accountId, int? pmId, PatchPaymentParams data = null)
        {
             ApiResponse<PaymentFull> localVarResponse = PatchAccountPaymentMethodWithHttpInfo(accountId, pmId, data);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Replace the status of an individual payment method. Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>ApiResponse of PaymentFull</returns>
        public ApiResponse< PaymentFull > PatchAccountPaymentMethodWithHttpInfo (int? accountId, int? pmId, PatchPaymentParams data = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->PatchAccountPaymentMethod");
            // verify the required parameter 'pmId' is set
            if (pmId == null)
                throw new ApiException(400, "Missing required parameter 'pmId' when calling PaymentmethodsApi->PatchAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods/{pm_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (pmId != null) localVarPathParams.Add("pm_id", Configuration.ApiClient.ParameterToString(pmId)); // path parameter
            if (data != null && data.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
            }
            else
            {
                localVarPostBody = data; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PatchAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PaymentFull>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PaymentFull) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaymentFull)));
        }

        /// <summary>
        /// Replace the status of an individual payment method. Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>Task of PaymentFull</returns>
        public async System.Threading.Tasks.Task<PaymentFull> PatchAccountPaymentMethodAsync (int? accountId, int? pmId, PatchPaymentParams data = null)
        {
             ApiResponse<PaymentFull> localVarResponse = await PatchAccountPaymentMethodAsyncWithHttpInfo(accountId, pmId, data);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Replace the status of an individual payment method. Replace the status of an individual payment method. See Account Payment Methods for more info on the properties.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Account ID</param>
        /// <param name="pmId">Payment Method ID</param>
        /// <param name="data">Payment data (optional)</param>
        /// <returns>Task of ApiResponse (PaymentFull)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PaymentFull>> PatchAccountPaymentMethodAsyncWithHttpInfo (int? accountId, int? pmId, PatchPaymentParams data = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling PaymentmethodsApi->PatchAccountPaymentMethod");
            // verify the required parameter 'pmId' is set
            if (pmId == null)
                throw new ApiException(400, "Missing required parameter 'pmId' when calling PaymentmethodsApi->PatchAccountPaymentMethod");

            var localVarPath = "/accounts/{account_id}/payment-methods/{pm_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (accountId != null) localVarPathParams.Add("account_id", Configuration.ApiClient.ParameterToString(accountId)); // path parameter
            if (pmId != null) localVarPathParams.Add("pm_id", Configuration.ApiClient.ParameterToString(pmId)); // path parameter
            if (data != null && data.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
            }
            else
            {
                localVarPostBody = data; // byte array
            }

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PatchAccountPaymentMethod", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PaymentFull>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PaymentFull) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PaymentFull)));
        }

    }
}
